/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 * 
 * Created on Apr 8, 2012, 4:31:02 PM
 */
package PresentationLayer;

import java.awt.event.ComponentListener;
import java.awt.event.ContainerListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.imgscalr.Scalr;
import LogicLayer.BL_Keyboard;
import LogicLayer.ImageHandler;
import java.awt.AWTEventMulticaster;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowStateListener;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.AttributedCharacterIterator;
import java.text.AttributedString;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import static org.imgscalr.Scalr.*;

/**
 *
 * @author Dempsey, Geoffrey, Jens
 * // http://wiki.processing.org/w/Open_Files_through_a_GUI
 */
public class GUI extends javax.swing.JFrame {
	// Business Layer object
	private BL_Keyboard bl;
	// Business Layer image handler
	private ImageHandler ih;
	// Distance to move the machine head
	private double distance;
	// The image that is loaded
	private BufferedImage bufferedImage;
	// List with gcode commands
	private ArrayList<String> gcode;
	private static final String newline = "\n";


	
	/** Creates new form NewJFrame */
	public GUI() {
		initComponents();
                
                //WAIT FOR WINDOW TO DISPLAY
                this.addWindowListener(new WindowListener() {

                        @Override
                        public void windowOpened(WindowEvent e) {

                            System.out.println("Application opened");
                            init();
                        }

                        @Override
                        public void windowClosing(WindowEvent e) {}

                        @Override
                        public void windowClosed(WindowEvent e) {}

                        @Override
                        public void windowIconified(WindowEvent e) {}

                        @Override
                        public void windowDeiconified(WindowEvent e) {}

                        @Override
                        public void windowActivated(WindowEvent e) {}

                        @Override
                        public void windowDeactivated(WindowEvent e) {}
                });
                
		this.distance = 0.1;
		
                jTextPaneMessages.setEditable(false);
                appendText("Scanning for serial ports, this may take a while... Meanwhile the program may not respond", Color.BLUE);
	}
        
        
        /**
         * Method inits the datalayer AFTER the window is showed
         */
        private void init() {         
            //wait a while for text to add to displaybox
            try {Thread.sleep(1000);} 
            catch (Exception evt) {}

            //init datalayer
            bl = new BL_Keyboard();


            //get all available ports from business layer and add them to dropdown box
            ArrayList<String> ports = bl.getPortList();

            for(int i = 0; i < ports.size(); i++) {
                    jComboBoxPorts.addItem(ports.get(i));
            }

            appendText("Scanning complete, you can now select the COM port above", Color.BLUE);
        }
        
	
        
        /**
         * Method which appends text to the GUI console textfield
         * @param text
         * @param color 
         */
	public static void appendText(String text, Color color) {
		try {
			SimpleAttributeSet set = new SimpleAttributeSet();
			jTextPaneMessages.setCharacterAttributes(set, true);
			StyleConstants.setForeground(set, color);
			Document doc = jTextPaneMessages.getStyledDocument();
			doc.insertString(doc.getLength(), text + newline, set);	
		}
		catch (BadLocationException ex) {
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonLoadImage = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jLabelConvertedImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonConvert = new javax.swing.JButton();
        jButtonSend = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPaneLayers = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPaneDepth = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPaneDiameter = new javax.swing.JTextPane();
        jLabelHeight = new javax.swing.JLabel();
        jLabelWidth = new javax.swing.JLabel();
        jSliderScale = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonUp = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        jButtonDown = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        dropdownDistance = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonZUP = new javax.swing.JButton();
        jButtonZDOWN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPaneOneLine = new javax.swing.JTextPane();
        jButtonSendOne = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButtonBrowseGcode = new javax.swing.JButton();
        jLabelSelectedFile = new javax.swing.JLabel();
        jButtonSendGcode = new javax.swing.JButton();
        jPanelMachineText = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPaneMessages = new javax.swing.JTextPane();
        jButtonConnect = new javax.swing.JButton();
        jComboBoxPorts = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxFeed = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jScrollPane4.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonLoadImage.setText("Browse Image..");
        jButtonLoadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadImageActionPerformed(evt);
            }
        });

        jLabelImage.setMaximumSize(new java.awt.Dimension(18, 20));

        jLabel2.setText("Converted Image");

        jButtonConvert.setText("Convert");
        jButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertActionPerformed(evt);
            }
        });

        jButtonSend.setText("Send");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        jLabel12.setText("Here you can load an image, then convert it to gCode, and finally send it to the machine");

        jLabel10.setText("Parameters");

        jLabel13.setText("Layers");

        jTextPaneLayers.setText("1");
        jScrollPane1.setViewportView(jTextPaneLayers);

        jLabel14.setText("Depth");

        jTextPaneDepth.setText("2");
        jScrollPane2.setViewportView(jTextPaneDepth);

        jLabel15.setText("Diameter");

        jTextPaneDiameter.setText("2");
        jScrollPane3.setViewportView(jTextPaneDiameter);

        jSliderScale.setMaximum(180);
        jSliderScale.setMinimum(10);
        jSliderScale.setPaintLabels(true);
        jSliderScale.setPaintTicks(true);
        jSliderScale.setSnapToTicks(true);
        jSliderScale.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderScaleStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel19.setText("mm");

        jLabel20.setText("mm");

        jLabel16.setText("Width:");

        jLabel17.setText("Height:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addContainerGap(225, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13))
                                .addGap(15, 15, 15))
                            .addComponent(jLabel15))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(jSliderScale, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addGap(176, 176, 176)
                                                .addComponent(jLabel16)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelWidth)
                                                .addGap(25, 25, 25)
                                                .addComponent(jLabel17)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelHeight)))))
                                .addContainerGap(68, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                            .addComponent(jButtonLoadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(119, 119, 119)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelConvertedImage, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                            .addComponent(jLabel2))
                                        .addGap(96, 96, 96)
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(181, 181, 181)
                                        .addComponent(jButtonConvert)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 310, Short.MAX_VALUE)
                                        .addComponent(jButtonSend)))
                                .addGap(32, 32, 32))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonLoadImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelConvertedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonConvert)
                        .addComponent(jButtonSend)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(jLabel14)
                                .addGap(15, 15, 15))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel20)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jSliderScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelWidth)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabelHeight))))
                .addGap(216, 216, 216))
        );

        jTabbedPane1.addTab("X SCAN", jPanel2);

        jButtonUp.setText("UP");
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });

        leftButton.setText("LEFT");
        leftButton.setName("leftButton"); // NOI18N
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        jButtonDown.setText("DOWN");
        jButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownActionPerformed(evt);
            }
        });

        rightButton.setText("RIGHT");
        rightButton.setName("rightButton"); // NOI18N
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        dropdownDistance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.1", "0.2", "0.5", "1.0", "5.0", "10.0" }));
        dropdownDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownDistanceActionPerformed(evt);
            }
        });

        jLabel1.setText("cm");

        jLabel5.setText("X / Y Positioning");

        jLabel6.setText("Z Positioning");

        jButtonZUP.setText("UP");
        jButtonZUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZUPActionPerformed(evt);
            }
        });

        jButtonZDOWN.setText("DOWN");
        jButtonZDOWN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZDOWNActionPerformed(evt);
            }
        });

        jLabel7.setText("Parameters");

        jLabel8.setText("Distance");

        jLabel11.setText("Here you can control the machine by setting a distance and pressing the control buttons");

        jLabel18.setText("Send Code");

        jScrollPane6.setViewportView(jTextPaneOneLine);

        jButtonSendOne.setText("Send");
        jButtonSendOne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendOneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addComponent(dropdownDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(jLabel5))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(68, 68, 68)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jButtonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jButtonDown))))
                                        .addGap(106, 106, 106)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jButtonZUP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonZDOWN)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(leftButton)
                                        .addGap(75, 75, 75)
                                        .addComponent(rightButton))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSendOne)))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUp)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(leftButton)
                                    .addComponent(rightButton))))
                        .addGap(14, 14, 14)
                        .addComponent(jButtonDown))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonZUP)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonZDOWN))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dropdownDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSendOne))
                .addGap(91, 91, 91))
        );

        jTabbedPane1.addTab("Motor Control", jPanel3);

        jLabel9.setText("Here you can just select your .Gcode file to execute");

        jButtonBrowseGcode.setText("Browse..");
        jButtonBrowseGcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseGcodeActionPerformed(evt);
            }
        });

        jLabelSelectedFile.setText("selected File");

        jButtonSendGcode.setText("Send");
        jButtonSendGcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendGcodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButtonBrowseGcode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelSelectedFile)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSendGcode)))
                .addContainerGap(434, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectedFile)
                    .addComponent(jButtonBrowseGcode)
                    .addComponent(jButtonSendGcode))
                .addContainerGap(290, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Load Gcode", jPanel4);

        jPanelMachineText.setBackground(new java.awt.Color(255, 255, 255));

        jTextPaneMessages.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane5.setViewportView(jTextPaneMessages);

        javax.swing.GroupLayout jPanelMachineTextLayout = new javax.swing.GroupLayout(jPanelMachineText);
        jPanelMachineText.setLayout(jPanelMachineTextLayout);
        jPanelMachineTextLayout.setHorizontalGroup(
            jPanelMachineTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMachineTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 696, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMachineTextLayout.setVerticalGroup(
            jPanelMachineTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMachineTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButtonConnect.setLabel("CONNECT");
        jButtonConnect.setName("connect"); // NOI18N
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jLabel3.setText("Please select a COM port from the Dropdown list and click Connect.");

        jComboBoxFeed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "50", "75", "100", "125", "150" }));
        jComboBoxFeed.setSelectedIndex(4);
        jComboBoxFeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFeedActionPerformed(evt);
            }
        });

        jLabel4.setText("Feedrate");

        jMenu1.setText("Menu");

        jMenuItemSave.setLabel("Save");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemSave);

        jMenuItem2.setText("About");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setLabel("Exit");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButtonConnect)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxFeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelMachineText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonConnect)
                            .addComponent(jComboBoxPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxFeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)))
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMachineText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        getAccessibleContext().setAccessibleName("frame1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
	//rekening houden met dropdown van afstand
	bl.setCommand("LEFT", this.distance);
}//GEN-LAST:event_leftButtonActionPerformed

private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
	bl.setCommand("RIGHT", this.distance);
}//GEN-LAST:event_rightButtonActionPerformed

private void dropdownDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownDistanceActionPerformed
	this.distance = Double.parseDouble(dropdownDistance.getSelectedItem().toString());
}//GEN-LAST:event_dropdownDistanceActionPerformed

private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
	bl.startConnection((String)jComboBoxPorts.getSelectedItem());
}//GEN-LAST:event_jButtonConnectActionPerformed

private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
	bl.setCommand("UP", this.distance);
}//GEN-LAST:event_jButtonUpActionPerformed

private void jButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed
	bl.setCommand("DOWN", this.distance);
}//GEN-LAST:event_jButtonDownActionPerformed

private void jButtonLoadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadImageActionPerformed
	File inputFile = null;
	JFileChooser fd = new JFileChooser(".");
	int returnVal = fd.showOpenDialog(null);
	if (returnVal == JFileChooser.APPROVE_OPTION) {
		inputFile = fd.getSelectedFile();
	}
   
	try {
		this.bufferedImage = ImageIO.read(inputFile);
		BufferedImage thumbnail = Scalr.resize(bufferedImage, 150);
		jLabelImage.setIcon(new ImageIcon(thumbnail));
		jLabelHeight.setText(Integer.toString(bufferedImage.getHeight()));
		jLabelWidth.setText(Integer.toString(bufferedImage.getWidth()));
	} catch (IOException ex) {
		JOptionPane.showMessageDialog( null, ex.toString() );
		appendText(ex.toString(), Color.red);
	}
}//GEN-LAST:event_jButtonLoadImageActionPerformed

private void jButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertActionPerformed
	if (this.jLabelImage.getIcon() == null) {
		appendText("Please first load an image", Color.red);
	}
	else {
		// width in mm, diameter frees in mm, aantal lagen, diepte)
		int diameter = Integer.parseInt(this.jTextPaneDiameter.getText());
		int layers = Integer.parseInt(this.jTextPaneLayers.getText());
		int depth = Integer.parseInt(this.jTextPaneDepth.getText());
		int width = Integer.parseInt(jLabelWidth.getText());
		this.gcode = bl.createImage(this.bufferedImage, diameter, layers, depth, width);
		BufferedImage img = bl.getImage();
		BufferedImage thumbnail = Scalr.resize(img, 150);
		jLabelConvertedImage.setIcon(new ImageIcon(thumbnail));
	}
}//GEN-LAST:event_jButtonConvertActionPerformed

private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1MouseClicked

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
	System.exit(0);
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jButtonZUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZUPActionPerformed
	bl.setCommand("ZUP", this.distance);
}//GEN-LAST:event_jButtonZUPActionPerformed

private void jButtonZDOWNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZDOWNActionPerformed
	bl.setCommand("ZDOWN", this.distance);
}//GEN-LAST:event_jButtonZDOWNActionPerformed

private void jButtonBrowseGcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseGcodeActionPerformed
	JFileChooser fc = new JFileChooser();
	this.gcode = new ArrayList<String>();
	
	int returnVal = fc.showOpenDialog(this);
	
	if (returnVal == JFileChooser.APPROVE_OPTION) {
		File f = fc.getSelectedFile();
		jLabelSelectedFile.setText(f.getName());
		//if (file.getName().endsWith("gcode")) {	
		//}
		try {
			BufferedReader inFile = new BufferedReader(new FileReader(f));
			String in = inFile.readLine();
			while (in != null) {
				this.gcode.add(in);
				in = inFile.readLine();
			}
			inFile.close();
			
		}
		catch(FileNotFoundException exc) {
			// Should not trigger
		}
		catch(IOException exc) {
			appendText("Error reading file", Color.red);
		}
	}
}//GEN-LAST:event_jButtonBrowseGcodeActionPerformed

private void jButtonSendGcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendGcodeActionPerformed
	if (this.gcode == null) {
		appendText("You have to select a file first", Color.red);
	}
	else {
		bl.sendFile(this.gcode);
	}
}//GEN-LAST:event_jButtonSendGcodeActionPerformed

private void jSliderScaleStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderScaleStateChanged
	appendText(Integer.toString(jSliderScale.getValue()), Color.red);
	int width = this.bufferedImage.getWidth();
	int height = this.bufferedImage.getHeight();	
	
	if (width > height) {
		double scaleImage = height / width;
		this.jLabelWidth.setText(Integer.toString(jSliderScale.getValue()));
		this.jLabelHeight.setText(Double.toString(scaleImage * jSliderScale.getValue()));
	}
	else {
		double scaleImage = width / height;
		this.jLabelHeight.setText(Integer.toString(jSliderScale.getValue()));
		this.jLabelWidth.setText(Double.toString(scaleImage * jSliderScale.getValue()));		
	}
	//BufferedImage scaledImage = new BufferedImage(bufferedImage.getWidth() / 2, bufferedImage.getHeight() / 2, BufferedImage.TYPE_INT_ARGB);
	
	//Graphics2D graphics2D = scaledImage.createGraphics();
	//graphics2D.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
	//graphics2D.drawImage(bufferedImage, 0, 0, bufferedImage.getWidth() / 2, bufferedImage.getHeight() / 2, null);

}//GEN-LAST:event_jSliderScaleStateChanged

private void jComboBoxFeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFeedActionPerformed
	bl.setFeedRate("F" + jComboBoxFeed.getSelectedItem().toString());
}//GEN-LAST:event_jComboBoxFeedActionPerformed

private void jButtonSendOneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendOneActionPerformed
	if (this.jTextPaneOneLine.getText() == null || this.jTextPaneOneLine.getText().trim().equals( "" )) {
		appendText("You have to enter a line of code first", Color.red);
	}
	else {
		bl.sendCommand(this.jTextPaneOneLine.getText());
	}
}//GEN-LAST:event_jButtonSendOneActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        if (this.gcode != null) {
            bl.sendFile(this.gcode);
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
 	try {
		FileWriter writer = new FileWriter("save.gcode");
			for (String str: gcode) {
				writer.write(str);
			}
			
			writer.close();
		} catch (IOException ex) {
			appendText(ex.toString(), Color.red);
		}
}//GEN-LAST:event_jMenuItemSaveActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
	JOptionPane.showMessageDialog(this,
    "Made by Geoffrey, Jens & Dempsey.",
    "3D Mini CNC Software",
    JOptionPane.INFORMATION_MESSAGE);
}//GEN-LAST:event_jMenuItem2ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new GUI().setVisible(true);
			}
		});
	}
	
	public void keyPressed(KeyEvent e) {
		int keyCode = e.getKeyCode();
		switch(keyCode) { 
			case KeyEvent.VK_UP:
					bl.setCommand("UP", this.distance);
				break;
			case KeyEvent.VK_DOWN:
					bl.setCommand("DOWN", this.distance);
				break;
			case KeyEvent.VK_LEFT:
					bl.setCommand("LEFT", this.distance);
				break;
			case KeyEvent.VK_RIGHT :
					bl.setCommand("RIGHT", this.distance);	
				break;
		}	
		
	}
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox dropdownDistance;
    private javax.swing.JButton jButtonBrowseGcode;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonConvert;
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonLoadImage;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JButton jButtonSendGcode;
    private javax.swing.JButton jButtonSendOne;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JButton jButtonZDOWN;
    private javax.swing.JButton jButtonZUP;
    private javax.swing.JComboBox jComboBoxFeed;
    private javax.swing.JComboBox jComboBoxPorts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConvertedImage;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelSelectedFile;
    private javax.swing.JLabel jLabelWidth;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelMachineText;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSlider jSliderScale;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPaneDepth;
    private javax.swing.JTextPane jTextPaneDiameter;
    private javax.swing.JTextPane jTextPaneLayers;
    private static javax.swing.JTextPane jTextPaneMessages;
    private javax.swing.JTextPane jTextPaneOneLine;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton rightButton;
    // End of variables declaration//GEN-END:variables
}
