/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 * 
 * Created on Apr 8, 2012, 4:31:02 PM
 */
package PresentationLayer;

import LogicLayer.BL_Keyboard;
import LogicLayer.ImageHandler;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Dempsey, Geoffrey, Jens
 * // http://wiki.processing.org/w/Open_Files_through_a_GUI
 */
public class GUI extends javax.swing.JFrame {
	// Business Layer object
	private BL_Keyboard bl;
	// Business Layer image handler
	private ImageHandler ih;
	// Distance to move the machine head
	private double distance;
	// The image that is loaded
	private BufferedImage bufferedImage;
	// List with gcode commands
	private ArrayList<String> gcode;

	
	/** Creates new form NewJFrame */
	public GUI() {
		initComponents();
		this.bl = new BL_Keyboard();
		this.distance = 0.1;
                
                //get all available ports from business layer and add them to dropdown box
                ArrayList<String> ports = bl.getPortList();
                
                for(int i = 0; i < ports.size(); i++) {
                    jComboBoxPorts.addItem(ports.get(i));
                }
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonConnect = new javax.swing.JButton();
        jComboBoxPorts = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonLoadImage = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jLabelConvertedImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonConvert = new javax.swing.JButton();
        jButtonSend = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButtonUp = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        jButtonDown = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        dropdownDistance = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonZUP = new javax.swing.JButton();
        jButtonZDOWN = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButtonBrowseGcode = new javax.swing.JButton();
        jLabelSelectedFile = new javax.swing.JLabel();
        jButtonSendGcode = new javax.swing.JButton();
        jLabelErrorLoad = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonConnect.setLabel("CONNECT");
        jButtonConnect.setName("connect"); // NOI18N
        jButtonConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConnectActionPerformed(evt);
            }
        });

        jLabel3.setText("Please select a COM port from the Dropdown list and click Connect.");

        jLabel4.setText("If the list is empty, make sure that the machine is properly connected, and try again.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonConnect)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConnect)
                    .addComponent(jComboBoxPorts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Connection", jPanel1);

        jButtonLoadImage.setText("Browse Image..");
        jButtonLoadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoadImageActionPerformed(evt);
            }
        });

        jLabel2.setText("Converted Image");

        jButtonConvert.setText("CONVERT");
        jButtonConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvertActionPerformed(evt);
            }
        });

        jButtonSend.setText("Send");

        jLabel12.setText("Here you can load an image, then convert it to gCode, and finally send it to the machine");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(jButtonLoadImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabelConvertedImage, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addGap(205, 205, 205))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jButtonConvert)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 256, Short.MAX_VALUE)
                        .addComponent(jButtonSend)))
                .addGap(65, 65, 65))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(141, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelConvertedImage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonLoadImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConvert)
                    .addComponent(jButtonSend))
                .addGap(44, 44, 44))
        );

        jTabbedPane1.addTab("X SCAN", jPanel2);

        jButtonUp.setText("UP");
        jButtonUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpActionPerformed(evt);
            }
        });

        leftButton.setText("LEFT");
        leftButton.setName("leftButton"); // NOI18N
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        jButtonDown.setText("DOWN");
        jButtonDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDownActionPerformed(evt);
            }
        });

        rightButton.setText("RIGHT");
        rightButton.setName("rightButton"); // NOI18N
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        dropdownDistance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.1", "0.2", "0.5", "1.0", "5.0", "10.0" }));
        dropdownDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownDistanceActionPerformed(evt);
            }
        });

        jLabel1.setText("cm");

        jLabel5.setText("X / Y Positioning");

        jLabel6.setText("Z Positioning");

        jButtonZUP.setText("UP");
        jButtonZUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZUPActionPerformed(evt);
            }
        });

        jButtonZDOWN.setText("DOWN");
        jButtonZDOWN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZDOWNActionPerformed(evt);
            }
        });

        jLabel7.setText("Parameters");

        jLabel8.setText("Distance");

        jLabel11.setText("Here you can control the machine by setting a distance and pressing the control buttons");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addComponent(dropdownDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(83, 83, 83)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel5))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(68, 68, 68)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonUp, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonDown))))
                                .addGap(106, 106, 106)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jButtonZUP, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonZDOWN)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(leftButton)
                                .addGap(75, 75, 75)
                                .addComponent(rightButton)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonUp)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(leftButton)
                                    .addComponent(rightButton))))
                        .addGap(14, 14, 14)
                        .addComponent(jButtonDown))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonZUP)
                        .addGap(14, 14, 14)
                        .addComponent(jButtonZDOWN))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dropdownDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addComponent(jLabel7))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Motor Control", jPanel3);

        jLabel9.setText("Here you can just select your .Gcode file to execute");

        jButtonBrowseGcode.setText("Browse..");
        jButtonBrowseGcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseGcodeActionPerformed(evt);
            }
        });

        jLabelSelectedFile.setText("\"SelectedFile\"");

        jButtonSendGcode.setText("Send");
        jButtonSendGcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendGcodeActionPerformed(evt);
            }
        });

        jLabelErrorLoad.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorLoad.setText("ErrorText");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelErrorLoad)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jButtonBrowseGcode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelSelectedFile)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSendGcode)))))
                .addContainerGap(350, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSelectedFile)
                    .addComponent(jButtonBrowseGcode)
                    .addComponent(jButtonSendGcode))
                .addGap(33, 33, 33)
                .addComponent(jLabelErrorLoad)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Load Gcode", jPanel4);

        jMenu1.setText("File");

        jMenuItemOpen.setLabel("Open");
        jMenu1.add(jMenuItemOpen);

        jMenuItemSave.setLabel("Save");
        jMenu1.add(jMenuItemSave);

        jMenuItem1.setLabel("Exit");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem1MouseClicked(evt);
            }
        });
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("About");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("frame1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
	//rekening houden met dropdown van afstand
	bl.setCommand("LEFT", this.distance);
}//GEN-LAST:event_leftButtonActionPerformed

private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
	bl.setCommand("RIGHT", this.distance);
}//GEN-LAST:event_rightButtonActionPerformed

private void dropdownDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownDistanceActionPerformed
	this.distance = Double.parseDouble(dropdownDistance.getSelectedItem().toString());
}//GEN-LAST:event_dropdownDistanceActionPerformed

private void jButtonConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConnectActionPerformed
	System.out.println((String)jComboBoxPorts.getSelectedItem());
	bl.startConnection((String)jComboBoxPorts.getSelectedItem());
}//GEN-LAST:event_jButtonConnectActionPerformed

private void jButtonUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpActionPerformed
	bl.setCommand("UP", this.distance);
}//GEN-LAST:event_jButtonUpActionPerformed

private void jButtonDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDownActionPerformed
	bl.setCommand("DOWN", this.distance);
}//GEN-LAST:event_jButtonDownActionPerformed

private void jButtonLoadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoadImageActionPerformed
	File inputFile = null;
	JFileChooser fd = new JFileChooser(".");
	int returnVal = fd.showOpenDialog(null);
	if (returnVal == JFileChooser.APPROVE_OPTION) {
		inputFile = fd.getSelectedFile();
	}
   
	try {
		this.bufferedImage = ImageIO.read(inputFile);
		jLabelImage.setIcon(new ImageIcon(this.bufferedImage));
	} catch (IOException ex) {
		//Logger.getLogger(ImageReserveWerkend.class.getName()).log(Level.SEVERE, null, ex);
		JOptionPane.showMessageDialog( null, ex.toString() );
	}
//	try {
//
//		// Buffered read from file
//		BufferedImage image = bl.readImage("images.jpg");
//	  //Show the image inside the label
//		jLabelImage.setIcon(new ImageIcon(image));
//	} catch (Exception e) {
//	  //Display a message if something goes wrong
//	  JOptionPane.showMessageDialog( null, e.toString() );
//	}
}//GEN-LAST:event_jButtonLoadImageActionPerformed

private void jButtonConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvertActionPerformed
	this.ih = new ImageHandler(this.bufferedImage);
}//GEN-LAST:event_jButtonConvertActionPerformed

private void jMenuItem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MouseClicked
// TODO add your handling code here:
}//GEN-LAST:event_jMenuItem1MouseClicked

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
	System.exit(0);
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jButtonZUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZUPActionPerformed
	bl.setCommand("ZUP", this.distance);
}//GEN-LAST:event_jButtonZUPActionPerformed

private void jButtonZDOWNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZDOWNActionPerformed
	bl.setCommand("ZDOWN", this.distance);
}//GEN-LAST:event_jButtonZDOWNActionPerformed

private void jButtonBrowseGcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseGcodeActionPerformed
	JFileChooser fc = new JFileChooser();
	this.gcode = new ArrayList<String>();
	
	int returnVal = fc.showOpenDialog(this);
	
	if (returnVal == JFileChooser.APPROVE_OPTION) {
		File f = fc.getSelectedFile();
		jLabelSelectedFile.setText(f.getName());
		//if (file.getName().endsWith("gcode")) {	
		//}
		try {
			BufferedReader inFile = new BufferedReader(new FileReader(f));
			String in = inFile.readLine();
			while (in != null) {
				this.gcode.add(in);
				in = inFile.readLine();
			}
			inFile.close();
			
		}
		catch(FileNotFoundException exc) {
			// Should not trigger
		}
		catch(IOException exc) {
			jLabelErrorLoad.setText("Error reading file");
		}
	}
}//GEN-LAST:event_jButtonBrowseGcodeActionPerformed

private void jButtonSendGcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendGcodeActionPerformed
	if (this.gcode == null) {
		jLabelErrorLoad.setText("You have to select a file first");
	}
	else {
		jLabelErrorLoad.setText("");
		bl.sendFile(this.gcode);
	}
}//GEN-LAST:event_jButtonSendGcodeActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				new GUI().setVisible(true);
			}
		});
	}
	
	public void keyPressed(KeyEvent e) {
		int keyCode = e.getKeyCode();
		switch(keyCode) { 
			case KeyEvent.VK_UP:
					bl.setCommand("UP", this.distance);
				break;
			case KeyEvent.VK_DOWN:
					bl.setCommand("DOWN", this.distance);
				break;
			case KeyEvent.VK_LEFT:
					bl.setCommand("LEFT", this.distance);
				break;
			case KeyEvent.VK_RIGHT :
					bl.setCommand("RIGHT", this.distance);	
				break;
		}	
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox dropdownDistance;
    private javax.swing.JButton jButtonBrowseGcode;
    private javax.swing.JButton jButtonConnect;
    private javax.swing.JButton jButtonConvert;
    private javax.swing.JButton jButtonDown;
    private javax.swing.JButton jButtonLoadImage;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JButton jButtonSendGcode;
    private javax.swing.JButton jButtonUp;
    private javax.swing.JButton jButtonZDOWN;
    private javax.swing.JButton jButtonZUP;
    private javax.swing.JComboBox jComboBoxPorts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelConvertedImage;
    private javax.swing.JLabel jLabelErrorLoad;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelSelectedFile;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton rightButton;
    // End of variables declaration//GEN-END:variables
}
